### ISSUE TITLE
Slop terminates on startup arter throwing an instace of std::regex_error

### ISSUE THREAD

**Issue by jonnydark** [naelstrof/slop#86]
Just compiled this on Xubuntu 14.04

Running it from the command line causes it to terminate straight away.

```
terminate called after throwing an instance of std::regex_error
  what(): regex_error
Aborted (core dumpted)
```

**Comment by jonnydark** [comment]
Running under gdb gives this trace:

```
#0  0x00007ffff6dc6c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6dca028 in __GI_abort () at abort.c:89
#2  0x00007ffff76e218d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff76e0146 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff76e0191 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff76e03a8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7705165 in std::__throw_regex_error(std::regex_constants::error_type) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000000000046bc87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:974
#8  0x000000000046a38d in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:960
#9  0x0000000000468575 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:795
#10 0x0000000000465d50 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:773
#11 0x0000000000463938 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:758
#12 0x000000000046a27f in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:947
#13 0x0000000000468575 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:795
#14 0x0000000000465d50 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:773
#15 0x0000000000465d9a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:776
#16 0x0000000000465d9a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:776
#17 0x0000000000463938 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7fffffffdb40) at /usr/include/c++/4.8/bits/regex_compiler.h:758
#18 0x0000000000460b30 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler (this=0x7fffffffdb40, 
    __b=@0x7fffffffdc40: 0x475ad8 "--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)", __e=@0x7fffffffdc58: 0x475b0d "", __traits=..., __flags=16)
    at /usr/include/c++/4.8/bits/regex_compiler.h:729
#19 0x000000000045d979 in std::__detail::__compile<char const*, std::regex_traits<char> > (__b=@0x7fffffffdc40: 0x475ad8 "--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)", 
    __e=@0x7fffffffdc58: 0x475b0d "", __t=..., __f=16) at /usr/include/c++/4.8/bits/regex_compiler.h:1105
#20 0x000000000045b7f7 in std::basic_regex<char, std::regex_traits<char> >::basic_regex (this=0x68c8c0 <cxxopts::(anonymous namespace)::option_matcher>, 
    __p=0x475ad8 "--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)", __f=16) at /usr/include/c++/4.8/bits/regex.h:388
#21 0x00000000004566c5 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/jwilkinson/bin/slop/src/cxxopts.hpp:855
#22 0x0000000000456716 in _GLOBAL__sub_I__Z10parseColorSs () at /home/jwilkinson/bin/slop/src/main.cpp:305
#23 0x0000000000473cfd in __libc_csu_init ()
#24 0x00007ffff6db1ed5 in __libc_start_main (main=0x4565ce <main(int, char**)>, argc=1, argv=0x7fffffffddd8, init=0x473cb0 <__libc_csu_init>, fini=<optimised out>, rtld_fini=<optimised out>, 
    stack_end=0x7fffffffddc8) at libc-start.c:246
#25 0x0000000000451439 in _start ()
```

**Comment by naelstrof** [comment]
Which version of gcc or clang are you using to compile?
Do you have SLOP_UNICODE enabled or disabled?

**Comment by jonnydark** [comment]
Using g++ 4.8.4 which I appreciate is a bit old
I did try running cmake with-DSLOP_UNICODE=false as well as without and it didn't make a difference

**Comment by naelstrof** [comment]
https://github.com/jarro2783/cxxopts#requirements
Yeah that gcc is too old. I'll add detection for this issue in a bit.

You can fix it by updating gcc.

**Comment by jonnydark** [comment]
> The only build requirement is a C++ compiler that supports C++11 regular expressions. For example GCC >= 4.9 or clang with libc++.

Totally missed this apologies! Thanks 👍
